'use client';

import { useEffect, useState } from 'react';

/**
 * The code shown on a screen at the scan point, refreshed every window.
 *
 * The point of it is narrow: a photograph of this is useless within a minute,
 * where a photograph of the printed sheet is useful forever. It does not
 * replace the location check — nothing does — it just closes the easiest
 * shortcut.
 *
 * The SVG is fetched rather than generated here so there is one QR encoder in
 * the project, on the server, and the browser is not asked to carry one.
 */
export function RotatingQr({ scanPointId }: { scanPointId: string }) {
  const [svg, setSvg] = useState<string | null>(null);
  const [secondsLeft, setSecondsLeft] = useState<number | null>(null);
  const [failed, setFailed] = useState(false);

  useEffect(() => {
    let live = true;

    async function refresh() {
      try {
        const res = await fetch(`/api/hr/clock/qr?point=${encodeURIComponent(scanPointId)}`, {
          cache: 'no-store',
        });
        if (!res.ok) throw new Error(String(res.status));
        const data = (await res.json()) as { svg: string; expiresInSeconds: number };
        if (!live) return;
        setSvg(data.svg);
        setSecondsLeft(data.expiresInSeconds);
        setFailed(false);
      } catch {
        // A screen stuck on a dead code is worse than one that says so: people
        // would keep scanning something that cannot work.
        if (live) setFailed(true);
      }
    }

    void refresh();
    const tick = setInterval(() => {
      setSecondsLeft((s) => {
        if (s === null) return s;
        if (s <= 1) {
          void refresh();
          return null;
        }
        return s - 1;
      });
    }, 1000);

    return () => {
      live = false;
      clearInterval(tick);
    };
  }, [scanPointId]);

  if (failed) {
    return (
      <div className="card p-6 text-center text-sm text-[var(--color-status-cancelled)]">
        แสดงรหัสไม่ได้ — ใช้ QR ที่พิมพ์ติดผนังไปก่อน
      </div>
    );
  }

  return (
    <div className="card p-5 text-center">
      {svg ? (
        <div
          className="mx-auto w-[240px] [&>svg]:w-full [&>svg]:h-auto"
          // Generated by the server's QR encoder from a token this app signed;
          // no user input reaches it.
          dangerouslySetInnerHTML={{ __html: svg }}
        />
      ) : (
        <div className="mx-auto size-[240px] grid place-items-center text-[var(--color-muted)]">
          กำลังสร้างรหัส…
        </div>
      )}
      <p className="text-sm text-[var(--color-muted)] mt-2 tabular-nums">
        {secondsLeft === null ? 'กำลังรีเฟรช…' : `รหัสนี้ใช้ได้อีก ${secondsLeft} วินาที`}
      </p>
    </div>
  );
}
