import QRCode from 'qrcode';
import Link from 'next/link';
import { env } from '@/lib/env';
import { requirePermission } from '@/lib/auth/guard';
import { getScanPointPolicy } from '@/modules/hr/timeclock.service';
import { issueStaticToken } from '@/modules/hr/timeclock-token';
import { RotatingQr } from '@/components/hr/RotatingQr';

export const dynamic = 'force-dynamic';

const SCAN_POINT = 'OFFICE';

/**
 * Setting up the time clock: the code to print, the code to display, and where
 * the scan point is.
 *
 * Both codes exist because both were promised. They are not equivalent and the
 * page says which is which — the printed one is convenient and permanent, the
 * displayed one closes the photograph shortcut, and neither is the thing that
 * actually stops fraud.
 */
export default async function TimeClockSettingsPage() {
  await requirePermission('admin.config', '/settings/timeclock');

  const policy = await getScanPointPolicy();
  const staticToken = await issueStaticToken(SCAN_POINT, env().AUTH_SECRET);
  const staticUrl = `${env().APP_URL}/clock?t=${encodeURIComponent(staticToken)}`;
  const staticSvg = await QRCode.toString(staticUrl, {
    type: 'svg',
    margin: 1,
    // Higher correction than the screen code: this one gets printed, taped to
    // a wall, and lives in sunlight and fingerprints.
    errorCorrectionLevel: 'H',
  });

  return (
    <div className="space-y-5 max-w-3xl">
      <div>
        <h1 className="text-2xl">จุดลงเวลาและรหัส QR</h1>
        <p className="text-sm text-[var(--color-muted)] mt-1">
          พนักงานเปิดกล้องมือถือส่องรหัส แล้วหน้าลงเวลาจะเปิดขึ้นเอง ไม่ต้องติดตั้งแอป
        </p>
      </div>

      <div className="card p-4 text-[13px] space-y-2 bg-[var(--color-surface-alt)]">
        <p>
          <strong>ตัวป้องกันการโกงคือพิกัด ไม่ใช่ตัวรหัส QR</strong> — รหัสที่พิมพ์ติดผนัง
          ถูกถ่ายรูปส่งต่อได้ตั้งแต่สัปดาห์แรก สิ่งที่ผูกการลงเวลาเข้ากับสถานที่คือตำแหน่งของมือถือ
        </p>
        <p className="text-[var(--color-muted)]">
          และตำแหน่งจะไม่ปฏิเสธการลงเวลา — ถ้ามือถือหาพิกัดไม่ได้หรืออยู่นอกพื้นที่
          ระบบยังบันทึกเวลาให้ แต่ส่งเข้าคิวให้หัวหน้าตรวจ
          พนักงานต้องไม่เสียสิทธิ์เพราะโทรศัพท์
        </p>
      </div>

      <section>
        <h2 className="text-lg">พื้นที่ที่ยอมรับ</h2>
        <div className="card p-4 mt-2 space-y-2 text-sm">
          <div className="grid grid-cols-2 gap-2 max-w-sm">
            <span className="text-[var(--color-muted)]">ละติจูด</span>
            <span className="tabular-nums">{policy.office.lat}</span>
            <span className="text-[var(--color-muted)]">ลองจิจูด</span>
            <span className="tabular-nums">{policy.office.lng}</span>
            <span className="text-[var(--color-muted)]">รัศมี</span>
            <span className="tabular-nums">{policy.radiusMetres} เมตร</span>
          </div>

          {policy.isAssumption && (
            <p className="text-[13px] text-[var(--color-brand-orange)] pt-1">
              ⚠️ <strong>ยังเป็นค่าประมาณ</strong> — ค่านี้ตัดสินว่าการลงเวลาของใครผ่านหรือติดธง
              ควรไปยืนที่จุดที่จะติด QR เปิดแผนที่บนมือถือ อ่านพิกัดจริง แล้วนำมาแก้ที่{' '}
              <Link href="/settings/assumptions" className="underline">
                ค่าที่รอยืนยัน
              </Link>{' '}
              จากนั้นลดรัศมีลงเหลือ 50–100 เมตร
            </p>
          )}

          <a
            href={`https://www.google.com/maps?q=${policy.office.lat},${policy.office.lng}`}
            target="_blank"
            rel="noreferrer"
            className="text-[13px] text-[var(--color-brand-blue-600)] underline inline-block"
          >
            ดูตำแหน่งปัจจุบันบนแผนที่
          </a>
        </div>
      </section>

      <section>
        <h2 className="text-lg">รหัสสำหรับพิมพ์ติดผนัง</h2>
        <div className="card p-4 mt-2 flex flex-wrap items-center gap-4">
          <div
            className="w-[120px] shrink-0 [&>svg]:w-full [&>svg]:h-auto"
            // Generated by the server's QR encoder from a token this app
            // signed; no user input reaches it.
            dangerouslySetInnerHTML={{ __html: staticSvg }}
          />
          <div className="flex-1 min-w-[240px] space-y-2">
            <p className="text-[13px]">
              รหัสนี้ไม่มีวันหมดอายุ พิมพ์ครั้งเดียวติดไว้ได้ตลอด — และเพราะไม่หมดอายุ{' '}
              <strong>รูปถ่ายของมันก็ใช้ได้ตลอดเช่นกัน</strong> พิกัดคือสิ่งที่กันเรื่องนี้
            </p>
            <Link
              href="/print/timeclock-qr"
              className="inline-block bg-[var(--color-brand-orange)] text-white rounded-[3px] px-4 py-2 text-sm font-semibold"
            >
              เปิดหน้าป้ายสำหรับพิมพ์ (A4)
            </Link>
          </div>
        </div>
      </section>

      <section>
        <h2 className="text-lg">รหัสสำหรับแสดงบนจอ</h2>
        <p className="text-sm text-[var(--color-muted)] mt-1 mb-2">
          เปลี่ยนทุก 30 วินาที เหมาะกับจอหรือแท็บเล็ตที่จุดลงเวลา —
          รูปถ่ายของรหัสนี้ใช้ไม่ได้หลังผ่านไปไม่กี่วินาที
        </p>
        <RotatingQr scanPointId={SCAN_POINT} />
      </section>
    </div>
  );
}
